	<script>
	$(document).ready(function(){
		$('#search_text').keyup(function(){
			var txt = $(this).val();
			if(txt != ''){
				$.ajax({
					url:"tabelid/it_tabel.php",
					method:"post",
					data:{search:txt},
					dataType:"text",
					success:function(data){
						$('#result').html(data);
				}
			});
			}else{
					$('#result').html('');
				$.ajax({
					url:"tabelid/it_tabel.php",
					method:"post",
					data:{search:txt},
					dataType:"text",
					success:function(data){
						$('#result').html(data);
					}
				});
			}
		});
	});
    </script>